### ISSUE TITLE
Automated GUI tests

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#311]
**Estimated to 100**
We have often problem that suddenly some features stop to work...
May be it would be good to have also som GUI tests to be able automatically monitor every merge commit... (like login, register, add block, add course, ...)   

- [x] technology selection (jest) **2h** #322 
- [ ] workshop (optional) **2h**
- [x] proof of concept **6h** #322 
- [x] test scenario specification **10h** #330 
- [x] main functionality tests implementation **8h** #331 
- [x] check tests stability **8h** #333
